### PR TITLE
ensure a good understanding for winnus

### PR DESCRIPTION
**Pull request by OwenBrotherwood**
with a quick cut and paste hello.js as a base test of system

### CODE REVIEW

**Comment by OwenBrotherwood** [comment]
In order to ensure some tests etc and for me to fully understand winnus and nw.js I am preparing for the simplest test possible that can be a test program for winnus and nw.js as a nw.js application with the least amount of code possible.

This is my first cut and paste attempt and I have to find out a pain free PR for the work if this PR is OK: please consider pull and I can continue step by step.

Quick delve into nw.js (first time)

```
<!DOCTYPE html>
<html>
<head>
  <title>winnus with nw.js</title>
</head>
<body>
<script>
// get the system platform using node.js
var os = require('os');
var winnus = require('winnus');
document.write('You are running on ', os.platform());
var device = winnus.getDevices()[0];
winnus.connect(device, function(data) {
  document.write("Got data "+JSON.stringify(data));
});
winnus.write("Hello");
setTimeout(function() {
  winnus.disconnect();
}, 1000);
</script>
</body>
</html>

```

**Comment by gfwilliams** [comment]
Hi - looks good!

Do you think in future you could sort out all your commits *before* you issue a PR? I get an email for every change, and I've had around 300 emails from you in the past 3 weeks, which I end up ignoring because I can't read them all - I have no way of telling whether this PR (and the other PRs you've made) are actually ready to merge or not.

**Comment by OwenBrotherwood** [comment]
Will do: sorry, some like it "this way" others another way: ie need some form of PR doc for best practice for your way 
I do it better after some thought as to some mantra that I will come with if wished: I have a good way that may be in your liking

I also made a mistake: I pushed to master instead of a branch,

**IE if the input is _acceptable_ , then merge. Then I create a proper branch and apply best practice for the continuation of this doc effort without spam**

I will be able to use about 2hr's a day on this part of doc in the next couple of days (or as long as it takes)
Note of course that one is never finished, the main aim of this effort is to ensure that you do not need to use a week for Windows for a possible new release of the IDE as I will have hopefully a good setup so that I can help with Windows while  linux /chromebook can also come in scope for my testing if needed.

**Comment by OwenBrotherwood** [comment]
https://github.com/OwenBrotherwood/winnus/tree/docExample

**Pull request closed without merging**
